anchor_version = "0.25.0"
solana_version = "1.10.41"

[scripts]
test = "yarn mocha tests/**/*.spec.ts"

[provider]
cluster = "devnet"
wallet = "./oracle.json"

[programs.mainnet]
cardinal_stake_pool = "wfXTQapJ9XWsRTWA6W4EaNDizPn1oESNjBLMhoKkag7"
cardinal_reward_distributor = "J8KGQczjGYRvqDwMuQ6jBhZdFfLHzHmLTWZRuCCu6mrY"
cardinal_group_reward_distributor = "grwDL1AZiCaBmTQHTQVhX6wxXKowAnisDZxH7866LUL"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.devnet]
cardinal_stake_pool = "wfXTQapJ9XWsRTWA6W4EaNDizPn1oESNjBLMhoKkag7"
cardinal_reward_distributor = "J8KGQczjGYRvqDwMuQ6jBhZdFfLHzHmLTWZRuCCu6mrY"
cardinal_group_reward_distributor = "grwDL1AZiCaBmTQHTQVhX6wxXKowAnisDZxH7866LUL"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.testnet]
cardinal_stake_pool = "wfXTQapJ9XWsRTWA6W4EaNDizPn1oESNjBLMhoKkag7"
cardinal_reward_distributor = "J8KGQczjGYRvqDwMuQ6jBhZdFfLHzHmLTWZRuCCu6mrY"
cardinal_group_reward_distributor = "grwDL1AZiCaBmTQHTQVhX6wxXKowAnisDZxH7866LUL"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"

[programs.localnet]
cardinal_stake_pool = "wfXTQapJ9XWsRTWA6W4EaNDizPn1oESNjBLMhoKkag7"
cardinal_reward_distributor = "J8KGQczjGYRvqDwMuQ6jBhZdFfLHzHmLTWZRuCCu6mrY"
cardinal_group_reward_distributor = "grwDL1AZiCaBmTQHTQVhX6wxXKowAnisDZxH7866LUL"
cardinal_receipt_manager = "rrmevmpXMooxn8Qu6u7RWao93BZn4cKgfjtNMURSc2E"
